## 加载数据集

In [10]:
from datasets import load_dataset

eli5 = load_dataset("dany0407/eli5_category", split="train[:5000]")
eli5 = eli5.train_test_split(test_size=0.2)
eli5 = eli5.flatten() # 目标是 answers.text: []

## 平铺数据集

In [11]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("distilbert/distilgpt2")
def preprocess_function(examples):
    return tokenizer([" ".join(x) for x in examples["answers.text"]])

tokenized_eli5 = eli5.map(preprocess_function, batched=True, num_proc=4)
print(tokenized_eli5)

import json
print(json.dumps(tokenized_eli5["train"][0], ensure_ascii=False, indent=2))

Map (num_proc=4):   0%|          | 0/4000 [00:00<?, ? examples/s]

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (1312 > 1024). Running this sequence through the model will result in indexing errors
[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (1212 > 1024). Running this sequence through the model will result in indexing errors
[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (1100 > 1024). Running this sequence through the model will result in indexing errors
[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (1793 > 1024). Running this sequence through the model will result in indexing errors

Map (num_proc=4):   0%|          | 0/1000 [00:00<?, ? examples/s]

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (1576 > 1024). Running this sequence through the model will result in indexing errors
[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (1197 > 1024). Running this sequence through the model will result in indexing errors
[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (1710 > 1024). Running this sequence through the model will result in indexing errors
[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (2727 > 1024). Running this sequence through the model will result in indexing errors

DatasetDict({
    train: Dataset({
        features: ['q_id', 'title', 'selftext', 'category', 'subreddit', 'answers.a_id', 'answers.text', 'answers.score', 'answers.text_urls', 'title_urls', 'selftext_urls', 'input_ids', 'attention_mask'],
        num_rows: 4000
    })
    test: Dataset({
        features: ['q_id', 'title', 'selftext', 'category', 'subreddit', 'answers.a_id', 'answers.text', 'answers.score', 'answers.text_urls', 'title_urls', 'selftext_urls', 'input_ids', 'attention_mask'],
        num_rows: 1000
    })
})
{
  "q_id": "74wntd",
  "title": "Why does cold water help burns?",
  "selftext": "You would intuitively think that the burn damage is irreversible and not affected by the temperature of the skin after the burn.",
  "category": "Biology",
  "subreddit": "explainlikeimfive",
  "answers.a_id": [
    "do1mrrq",
    "do1nu7x"
  ],
  "answers.text": [
    "There's a few reasons that cold water is recommended for burns. First, depending on the burn and what caused it, there can be ongoing damage occurring- kind of like how scrambled eggs keep cooking for a bit even after you take them out of the pan; residual heat can still be doing harm after you've moved away from the source of the damage. If you were burned by something other than direct heat, like an acid, chemical or other damaging material, the water can help remove any traces remaining, **DEPENDING ON THE CHEMICAL**. You may want to *avoid* water in some situations, but that's usually going to be in scenarios where you should be trained and wearing safety gear. Additionally, cold water helps soothe the pain by numbing it. Also, it can help reduce and prevent immediate swelling.",
    "Have you ever heard that you should take your steak off the barbecue just a little bit before it is as rare/well done as you like it? Because the heat within the meat will continue to cook it after it has been taken off the grill. Your meat works exactly the same. The cells have so much heat that they transfer it deeper into your tissue, further damaging it. Cold water helps take that heat away before it has a chance to conduct deeper into you. Running water is used because burns are playgrounds for bacteria, and standing water collects bacteria really well, but if the water is always running out of the tap, nothing can collect in it, and thus on you."
  ],
  "answers.score": [
    7,
    4
  ],
  "answers.text_urls": [
    [],
    []
  ],
  "title_urls": [
    "url"
  ],
  "selftext_urls": [
    "url"
  ],
  "input_ids": [
    1858,
    338,
    257,
    1178,
    3840,
    326,
    4692,
    1660,
    318,
    7151,
    329,
    20246,
    13,
    3274,
    11,
    6906,
    319,
    262,
    4245,
    290,
    644,
    4073,
    340,
    11,
    612,
    460,
    307,
    7044,
    2465,
    14963,
    12,
    1611,
    286,
    588,
    703,
    34351,
    9653,
    1394,
    10801,
    329,
    257,
    1643,
    772,
    706,
    345,
    1011,
    606,
    503,
    286,
    262,
    3425,
    26,
    29598,
    4894,
    460,
    991,
    307,
    1804,
    4419,
    706,
    345,
    1053,
    3888,
    1497,
    422,
    262,
    2723,
    286,
    262,
    2465,
    13,
    1002,
    345,
    547,
    11544,
    416,
    1223,
    584,
    621,
    1277,
    4894,
    11,
    588,
    281,
    7408,
    11,
    5931,
    393,
    584,
    14790,
    2587,
    11,
    262,
    1660,
    460,
    1037,
    4781,
    597,
    20675,
    5637,
    11,
    12429,
    46162,
    10619,
    2751,
    6177,
    3336,
    5870,
    3620,
    20151,
    1174,
    13,
    921,
    743,
    765,
    284,
    1635,
    27080,
    9,
    1660,
    287,
    617,
    7445,
    11,
    475,
    326,
    338,
    3221,
    1016,
    284,
    307,
    287,
    13858,
    810,
    345,
    815,
    307,
    8776,
    290,
    5762,
    3747,
    7733,
    13,
    12032,
    11,
    4692,
    1660,
    5419,
    523,
    20388,
    262,
    2356,
    416,
    997,
    4623,
    340,
    13,
    4418,
    11,
    340,
    460,
    1037,
    4646,
    290,
    2948,
    7103,
    29844,
    13,
    8192,
    345,
    1683,
    2982,
    326,
    345,
    815,
    1011,
    534,
    26320,
    572,
    262,
    36646,
    655,
    257,
    1310,
    1643,
    878,
    340,
    318,
    355,
    4071,
    14,
    4053,
    1760,
    355,
    345,
    588,
    340,
    30,
    4362,
    262,
    4894,
    1626,
    262,
    6174,
    481,
    2555,
    284,
    4255,
    340,
    706,
    340,
    468,
    587,
    2077,
    572,
    262,
    29901,
    13,
    3406,
    6174,
    2499,
    3446,
    262,
    976,
    13,
    383,
    4778,
    423,
    523,
    881,
    4894,
    326,
    484,
    4351,
    340,
    9211,
    656,
    534,
    10712,
    11,
    2252,
    14790,
    340,
    13,
    10250,
    1660,
    5419,
    1011,
    326,
    4894,
    1497,
    878,
    340,
    468,
    257,
    2863,
    284,
    3189,
    9211,
    656,
    345,
    13,
    18162,
    1660,
    318,
    973,
    780,
    20246,
    389,
    24817,
    82,
    329,
    11492,
    11,
    290,
    5055,
    1660,
    26609,
    11492,
    1107,
    880,
    11,
    475,
    611,
    262,
    1660,
    318,
    1464,
    2491,
    503,
    286,
    262,
    9814,
    11,
    2147,
    460,
    2824,
    287,
    340,
    11,
    290,
    4145,
    319,
    345,
    13
  ],
  "attention_mask": [
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1
  ]
}

In [12]:
tokenized_eli5 = eli5.map(preprocess_function, batched=True, num_proc=4, remove_columns=eli5["train"].column_names)
print(tokenized_eli5["train"][0])

Map (num_proc=4):   0%|          | 0/4000 [00:00<?, ? examples/s]

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (1312 > 1024). Running this sequence through the model will result in indexing errors
[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (1212 > 1024). Running this sequence through the model will result in indexing errors
[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (1100 > 1024). Running this sequence through the model will result in indexing errors
[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (1793 > 1024). Running this sequence through the model will result in indexing errors

Map (num_proc=4):   0%|          | 0/1000 [00:00<?, ? examples/s]

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (1576 > 1024). Running this sequence through the model will result in indexing errors
[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (1197 > 1024). Running this sequence through the model will result in indexing errors
[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (1710 > 1024). Running this sequence through the model will result in indexing errors
[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (2727 > 1024). Running this sequence through the model will result in indexing errors

{'input_ids': [1858, 338, 257, 1178, 3840, 326, 4692, 1660, 318, 7151, 329, 20246, 13, 3274, 11, 6906, 319, 262, 4245, 290, 644, 4073, 340, 11, 612, 460, 307, 7044, 2465, 14963, 12, 1611, 286, 588, 703, 34351, 9653, 1394, 10801, 329, 257, 1643, 772, 706, 345, 1011, 606, 503, 286, 262, 3425, 26, 29598, 4894, 460, 991, 307, 1804, 4419, 706, 345, 1053, 3888, 1497, 422, 262, 2723, 286, 262, 2465, 13, 1002, 345, 547, 11544, 416, 1223, 584, 621, 1277, 4894, 11, 588, 281, 7408, 11, 5931, 393, 584, 14790, 2587, 11, 262, 1660, 460, 1037, 4781, 597, 20675, 5637, 11, 12429, 46162, 10619, 2751, 6177, 3336, 5870, 3620, 20151, 1174, 13, 921, 743, 765, 284, 1635, 27080, 9, 1660, 287, 617, 7445, 11, 475, 326, 338, 3221, 1016, 284, 307, 287, 13858, 810, 345, 815, 307, 8776, 290, 5762, 3747, 7733, 13, 12032, 11, 4692, 1660, 5419, 523, 20388, 262, 2356, 416, 997, 4623, 340, 13, 4418, 11, 340, 460, 1037, 4646, 290, 2948, 7103, 29844, 13, 8192, 345, 1683, 2982, 326, 345, 815, 1011, 534, 26320, 572, 262, 36646, 655, 257, 1310, 1643, 878, 340, 318, 355, 4071, 14, 4053, 1760, 355, 345, 588, 340, 30, 4362, 262, 4894, 1626, 262, 6174, 481, 2555, 284, 4255, 340, 706, 340, 468, 587, 2077, 572, 262, 29901, 13, 3406, 6174, 2499, 3446, 262, 976, 13, 383, 4778, 423, 523, 881, 4894, 326, 484, 4351, 340, 9211, 656, 534, 10712, 11, 2252, 14790, 340, 13, 10250, 1660, 5419, 1011, 326, 4894, 1497, 878, 340, 468, 257, 2863, 284, 3189, 9211, 656, 345, 13, 18162, 1660, 318, 973, 780, 20246, 389, 24817, 82, 329, 11492, 11, 290, 5055, 1660, 26609, 11492, 1107, 880, 11, 475, 611, 262, 1660, 318, 1464, 2491, 503, 286, 262, 9814, 11, 2147, 460, 2824, 287, 340, 11, 290, 4145, 319, 345, 13], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [13]:
input_text = tokenizer.decode(tokenized_eli5["train"][0]["input_ids"])
print(input_text)

There's a few reasons that cold water is recommended for burns. First, depending on the burn and what caused it, there can be ongoing damage occurring- kind of like how scrambled eggs keep cooking for a bit even after you take them out of the pan; residual heat can still be doing harm after you've moved away from the source of the damage. If you were burned by something other than direct heat, like an acid, chemical or other damaging material, the water can help remove any traces remaining, **DEPENDING ON THE CHEMICAL**. You may want to *avoid* water in some situations, but that's usually going to be in scenarios where you should be trained and wearing safety gear. Additionally, cold water helps soothe the pain by numbing it. Also, it can help reduce and prevent immediate swelling. Have you ever heard that you should take your steak off the barbecue just a little bit before it is as rare/well done as you like it? Because the heat within the meat will continue to cook it after it has been taken off the grill. Your meat works exactly the same. The cells have so much heat that they transfer it deeper into your tissue, further damaging it. Cold water helps take that heat away before it has a chance to conduct deeper into you. Running water is used because burns are playgrounds for bacteria, and standing water collects bacteria really well, but if the water is always running out of the tap, nothing can collect in it, and thus on you.

## 数据集分块

In [14]:
block_size = 128

def group_texts(examples):
    concatenated_examples = {k: sum(examples[k], []) for k in examples.keys()}
    total_length = len(concatenated_examples[list(examples.keys())[0]])
    if total_length >= block_size:
        total_length = (total_length // block_size) * block_size
    
    result = {
        k: [t[i: i + block_size] for i in range(0, total_length, block_size)]
        for k, t in concatenated_examples.items()
    }
    result["labels"] = result["input_ids"].copy()
    return result

lm_dataset = tokenized_eli5.map(group_texts, batched=True, num_proc=4)
print(lm_dataset["train"][0], )
print("input_ids=", lm_dataset["train"][0]["input_ids"])
print("input_ids len=", len(lm_dataset["train"][0]["input_ids"]))
print("labels=", lm_dataset["train"][0]["labels"])
print("labels len=", len(lm_dataset["train"][0]["labels"]))

print("input_ids==labels? ", lm_dataset["train"][0]["input_ids"] == lm_dataset["train"][0]["labels"])

Map (num_proc=4):   0%|          | 0/4000 [00:00<?, ? examples/s]

Map (num_proc=4):   0%|          | 0/1000 [00:00<?, ? examples/s]

{'input_ids': [1858, 338, 257, 1178, 3840, 326, 4692, 1660, 318, 7151, 329, 20246, 13, 3274, 11, 6906, 319, 262, 4245, 290, 644, 4073, 340, 11, 612, 460, 307, 7044, 2465, 14963, 12, 1611, 286, 588, 703, 34351, 9653, 1394, 10801, 329, 257, 1643, 772, 706, 345, 1011, 606, 503, 286, 262, 3425, 26, 29598, 4894, 460, 991, 307, 1804, 4419, 706, 345, 1053, 3888, 1497, 422, 262, 2723, 286, 262, 2465, 13, 1002, 345, 547, 11544, 416, 1223, 584, 621, 1277, 4894, 11, 588, 281, 7408, 11, 5931, 393, 584, 14790, 2587, 11, 262, 1660, 460, 1037, 4781, 597, 20675, 5637, 11, 12429, 46162, 10619, 2751, 6177, 3336, 5870, 3620, 20151, 1174, 13, 921, 743, 765, 284, 1635, 27080, 9, 1660, 287, 617, 7445, 11, 475, 326, 338, 3221], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'labels': [1858, 338, 257, 1178, 3840, 326, 4692, 1660, 318, 7151, 329, 20246, 13, 3274, 11, 6906, 319, 262, 4245, 290, 644, 4073, 340, 11, 612, 460, 307, 7044, 2465, 14963, 12, 1611, 286, 588, 703, 34351, 9653, 1394, 10801, 329, 257, 1643, 772, 706, 345, 1011, 606, 503, 286, 262, 3425, 26, 29598, 4894, 460, 991, 307, 1804, 4419, 706, 345, 1053, 3888, 1497, 422, 262, 2723, 286, 262, 2465, 13, 1002, 345, 547, 11544, 416, 1223, 584, 621, 1277, 4894, 11, 588, 281, 7408, 11, 5931, 393, 584, 14790, 2587, 11, 262, 1660, 460, 1037, 4781, 597, 20675, 5637, 11, 12429, 46162, 10619, 2751, 6177, 3336, 5870, 3620, 20151, 1174, 13, 921, 743, 765, 284, 1635, 27080, 9, 1660, 287, 617, 7445, 11, 475, 326, 338, 3221]}
input_ids= [1858, 338, 257, 1178, 3840, 326, 4692, 1660, 318, 7151, 329, 20246, 13, 3274, 11, 6906, 319, 262, 4245, 290, 644, 4073, 340, 11, 612, 460, 307, 7044, 2465, 14963, 12, 1611, 286, 588, 703, 34351, 9653, 1394, 10801, 329, 257, 1643, 772, 706, 345, 1011, 606, 503, 286, 262, 3425, 26, 29598, 4894, 460, 991, 307, 1804, 4419, 706, 345, 1053, 3888, 1497, 422, 262, 2723, 286, 262, 2465, 13, 1002, 345, 547, 11544, 416, 1223, 584, 621, 1277, 4894, 11, 588, 281, 7408, 11, 5931, 393, 584, 14790, 2587, 11, 262, 1660, 460, 1037, 4781, 597, 20675, 5637, 11, 12429, 46162, 10619, 2751, 6177, 3336, 5870, 3620, 20151, 1174, 13, 921, 743, 765, 284, 1635, 27080, 9, 1660, 287, 617, 7445, 11, 475, 326, 338, 3221]
input_ids len= 128
labels= [1858, 338, 257, 1178, 3840, 326, 4692, 1660, 318, 7151, 329, 20246, 13, 3274, 11, 6906, 319, 262, 4245, 290, 644, 4073, 340, 11, 612, 460, 307, 7044, 2465, 14963, 12, 1611, 286, 588, 703, 34351, 9653, 1394, 10801, 329, 257, 1643, 772, 706, 345, 1011, 606, 503, 286, 262, 3425, 26, 29598, 4894, 460, 991, 307, 1804, 4419, 706, 345, 1053, 3888, 1497, 422, 262, 2723, 286, 262, 2465, 13, 1002, 345, 547, 11544, 416, 1223, 584, 621, 1277, 4894, 11, 588, 281, 7408, 11, 5931, 393, 584, 14790, 2587, 11, 262, 1660, 460, 1037, 4781, 597, 20675, 5637, 11, 12429, 46162, 10619, 2751, 6177, 3336, 5870, 3620, 20151, 1174, 13, 921, 743, 765, 284, 1635, 27080, 9, 1660, 287, 617, 7445, 11, 475, 326, 338, 3221]
labels len= 128
input_ids==labels?  True

In [15]:
text = tokenizer.decode(lm_dataset["train"][0]["input_ids"])
print("text=", text)

text= There's a few reasons that cold water is recommended for burns. First, depending on the burn and what caused it, there can be ongoing damage occurring- kind of like how scrambled eggs keep cooking for a bit even after you take them out of the pan; residual heat can still be doing harm after you've moved away from the source of the damage. If you were burned by something other than direct heat, like an acid, chemical or other damaging material, the water can help remove any traces remaining, **DEPENDING ON THE CHEMICAL**. You may want to *avoid* water in some situations, but that's usually

## 将数据集转换为模型输入

In [16]:
from transformers import DataCollatorForLanguageModeling

# GPT-2 / DistilGPT2 有个特点：它原本没有专门的 pad_token
# 设置 pad_token 和 eos_token 相同
# 如果 batch 里有样本需要补齐长度，就用 eos_token 当作 padding token
tokenizer.pad_token = tokenizer.eos_token # eos = end of sequence
data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False # masked language modeling, true=BERT-style, false=GPT-2-style
)

## 训练

In [18]:
from transformers import AutoModelForCausalLM, TrainingArguments, Trainer

model = AutoModelForCausalLM.from_pretrained("distilbert/distilgpt2")

training_args = TrainingArguments(
    output_dir="my_awesome_eli5_clm-model",
    max_steps=200,                 # 先别完整 3 epoch
    per_device_train_batch_size=16,  # 可以试 16，看内存
    eval_strategy="steps",
    eval_steps=50,
    save_strategy="no",
    logging_steps=10,
    learning_rate=2e-5,
    weight_decay=0.01,
    push_to_hub=False,
    dataloader_pin_memory=False,   # 消掉 MPS pin_memory warning
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=lm_dataset["train"],
    eval_dataset=lm_dataset["test"],
    data_collator=data_collator,
    processing_class=tokenizer,
)

trainer.train()

Loading weights:   0%|          | 0/76 [00:00<?, ?it/s]

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'pad_token_id': 50256}.

TrainOutput(global_step=200, training_loss=3.9759389686584474, metrics={'train_runtime': 140.8586, 'train_samples_per_second': 22.718, 'train_steps_per_second': 1.42, 'total_flos': 104518700236800.0, 'train_loss': 3.9759389686584474, 'epoch': 0.3058103975535168})

In [19]:
import math

eval_results = trainer.evaluate()
print(f"Perplexity: {math.exp(eval_results['eval_loss']):.2f}")

Perplexity: 47.81

In [20]:
trainer.push_to_hub()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

CommitInfo(commit_url='https://huggingface.co/hedonwang/my_awesome_eli5_clm-model/commit/147c2fc05c36740c96eea2ab572ee1c4c3cece70', commit_message='End of training', commit_description='', oid='147c2fc05c36740c96eea2ab572ee1c4c3cece70', pr_url=None, repo_url=RepoUrl('https://huggingface.co/hedonwang/my_awesome_eli5_clm-model', endpoint='https://huggingface.co', repo_type='model', repo_id='hedonwang/my_awesome_eli5_clm-model'), pr_revision=None, pr_num=None)

## 推理

In [23]:
prompt = "Somatic hypermutation allows the immune system to"

from transformers import pipeline

generator = pipeline("text-generation", model=model, tokenizer=tokenizer)

generator(prompt)

[transformers] Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer GPT2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

[{'generated_text': "Somatic hypermutation allows the immune system to absorb the damage it causes. As it happens, our immune system is not constantly responding to threats, like a virus or bacteria or something like that. And the immune system is always acting as it does. So, if you're a fan of the original NES, you can make some more money. It's a little bit like the original NES. So, you can make some more money. The reason is because the NES doesn't have a Super Nintendo console. It's just a console, which does not have a Super Nintendo console. It's a console that does not have a Super Nintendo console. It's not used to do things like that. It does not have a Super Nintendo console. It's just a console that does not have a Super Nintendo console. It's just a console that does not have a Super Nintendo console. It's just a console that does not have a Super Nintendo console. It's just a console that does not have a Super Nintendo console. It's just a console that does not have a Super Nintendo console. It's just a console that simply does not have a Super Nintendo console. It's just a console that does not have a Super Nintendo console. It's just a console that does not have a Super Nintendo console. It's just"}]

In [ ]:
from transformers import AutoModelForCausalLM

model = AutoModelForCausalLM.from_pretrained("hedonwang/my_awesome_eli5_clm-model")
outputs = model.generate(inputs, max_new_tokens=100, do_sample=True, top_k=50, top_p=0.95)
tokenizer.batch_decode(outputs, skip_special_tokens=True)

model.safetensors:   0%|          | 0.00/328M [00:00<?, ?B/s]